# Generated by Django 4.1.2 on 2022-10-16 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Registration_date', models.DateField()),
                ('Num_of_courses_enrolled', models.IntegerField()),
                ('Num_of_courses_completed', models.IntegerField()),
                ('Qualification', models.TextField()),
                ('Introduction_brief', models.TextField()),
                ('Image', models.ImageField(upload_to='media')),
                ('Num_of_enrolled_students', models.IntegerField()),
                ('Average_review_rating', models.IntegerField()),
                ('Num_of_reviews', models.IntegerField()),
                ('About_website', models.TextField()),
                ('User_role', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
