# Generated by Django 4.1.2 on 2022-10-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Blog_content', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('Date_blog', models.DateField()),
                ('Approval_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('From_email', models.EmailField(max_length=254)),
                ('To_email', models.EmailField(max_length=254)),
                ('Message_content', models.TextField(default='Nil')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Introduction_brief',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Num_of_courses_completed',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Num_of_courses_enrolled',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Num_of_enrolled_students',
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('User_category', models.CharField(max_length=200)),
                ('Old_password', models.CharField(max_length=200)),
                ('New_password', models.CharField(max_length=200)),
                ('Req_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zial.registration')),
            ],
        ),
    ]
